language: java

jdk:
  - oraclejdk8

install: mvn install -DskipTests=true
script: mvn test

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
